### ISSUE TITLE
app_component.inject.dart No such file

### ISSUE THREAD

**Issue by jeanluc243** [zubairehman/flutter-boilerplate-project#15]
Compiler message:                                                       
lib/di/components/app_component.dart:7:8: Error: Error when reading 'lib/di/components/app_component.inject.dart': No such file or directory
import 'app_component.inject.dart' as g;                                
       ^                                                                
lib/di/components/app_component.dart:20:20: Error: Getter not found: 'AppComponent$Injector'.
    return await g.AppComponent$Injector.create(                        
                   ^^^^^^^^^^^^^^^^^^^^^                                
Compiler failed on /home/jeanluckabulu/Downloads/flutter-boilerplate-project-master/lib/main.dart

**Comment by zubairehman** [comment]
Hi,

As inject works with code generation, you need to use build runner to generate the required code. You can use this command:

`flutter packages pub run build_runner build`

or watch command in order to keep the source code synced automatically:

`flutter packages pub run build_runner watch`

for more details on DI, please check wiki:
https://github.com/zubairehman/flutter-boilerplate-project/wiki/Dependency-Injection

**Comment by jeanluc243** [comment]
i have this and it work well now thank @zubairehman for this packages :heart_eyes: 

flutter packages pub run build_runner build --delete-conflicting-outputs

**Comment by kadnan0900** [comment]
i have this and it work well  @zubairehman

flutter packages pub run build_runner build --delete-conflicting-outputs
